# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a370de067ee250e36d686878b99babbbc355a1f192d9a0ee15335306b42b31cc0d88317d8148da0dd89f13834aab538cdc39e60b2ab849e1220ce9f8006a511b

test:
  secret_key_base: 1eb75a0d90fa56da6b8b887d6c6acba3545841ee6faaa4a9a6ad74fbbc477cb73971aff0457e93647df15f0e6a040922b80f414bca1603b1b5d6badb90683525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
